name = "TAC Mods"
prefix = "tac"
author = "TAC Mod Team"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_tac_ca.paa",
    "logo_tac_small_ca.paa"
]

modname = "{{prefix}}_mods"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip {{prefix}}_mods_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

[scripts.extensions]
show_output = true
steps_windows = [
]
steps_linux = [
]
